apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "wc2026bot.fullname" . }}-log
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wc2026bot.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.storageClassName }}
