apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wc2026bot.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wc2026bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  BOT_TOKEN: "{{ .Values.env.BOT_TOKEN }}"
  CHAT_ID: "{{ .Values.env.CHAT_ID }}"
  CHECK_INTERVAL: "{{ .Values.env.CHECK_INTERVAL }}"
  FOOTBALL_API_KEY: "{{ .Values.env.FOOTBALL_API_KEY }}"
  LANG_BOT: "{{ .Values.env.LANG_BOT }}"
  SEND_TIME: "{{ .Values.env.SEND_TIME }}"
