apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "iptv.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secrets
    kind: ClusterSecretStore
  target:
    name: {{ include "iptv.fullname" . }}-env
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: iptv-secrets
