apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iptv.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "iptv.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.env }}
  {{ $k }}: "{{ $v }}"
  {{- end }}
