apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "alertmanager-telegram-bridge.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: kubernetes-secrets
    kind: ClusterSecretStore
  target:
    name: {{ include "alertmanager-telegram-bridge.fullname" . }}-config
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: bridge-secrets
