apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alertmanager-telegram-bridge.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
  labels:
    {{- include "alertmanager-telegram-bridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    server:
      host: "{{ .Values.config.server.host }}"
      port: {{ .Values.config.server.port }}
    telegram:
      token: "{{ .Values.config.telegram.token }}"
      default_chat_id: "{{ .Values.config.telegram.default_chat_id }}"
    throttle:
      repeat_interval: {{ .Values.config.throttle.repeat_interval }}
    quiet_hours:
      enabled: {{ .Values.config.quiet_hours.enabled }}
      start: "{{ .Values.config.quiet_hours.start }}"
      end: "{{ .Values.config.quiet_hours.end }}"
      timezone: "{{ .Values.config.quiet_hours.timezone }}"
    routes:
      {{- toYaml .Values.config.routes | nindent 6 }}
