apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: kubernetes-secrets
spec:
  provider:
    kubernetes:
      remoteNamespace: secrets
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: secrets
          key: ca.crt
      auth:
        serviceAccount:
          name: external-secrets
          namespace: external-secrets
