apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: iptv
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bibigon14/homelab-k3s.git
    targetRevision: main
    path: charts/iptv-traceroute-analyzer
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy: {}
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
