apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: tempo-distributed
    targetRevision: 1.61.3
    helm:
      values: |
        reportingEnabled: false
        extraObjects:
          - apiVersion: v1
            kind: Service
            metadata:
              name: tempo-query-frontend-nodeport
              namespace: monitoring
            spec:
              type: NodePort
              selector:
                app.kubernetes.io/component: query-frontend
                app.kubernetes.io/instance: tempo
              ports:
                - name: http
                  port: 3200
                  targetPort: 3200
                  nodePort: 30845
        minio:
          enabled: false
        ingester:
          replicas: 1
        distributor:
          replicas: 1
        querier:
          replicas: 1
        queryFrontend:
          replicas: 1
        compactor:
          replicas: 1
        storage:
          trace:
            backend: local
            local:
              path: /var/tempo/traces
            wal:
              path: /var/tempo/wal
        tempo:
          structuredConfig:
            ingester:
              lifecycler:
                ring:
                  replication_factor: 1
        traces:
          otlp:
            grpc:
              enabled: true
            http:
              enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
