apiVersion: v1
kind: Service
metadata:
  name: {{ include "river-bot.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "river-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "river-bot.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
