apiVersion: v1
kind: Service
metadata:
  name: homebridge-external
  namespace: default
spec:
  ports:
    - port: 8581
      targetPort: 8581
---
apiVersion: v1
kind: Endpoints
metadata:
  name: homebridge-external
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.50.212
    ports:
      - port: 8581
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homebridge
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`homebridge.homelab.local`)
      kind: Rule
      services:
        - name: homebridge-external
          port: 8581
  tls:
    secretName: homelab-tls
