apiVersion: v1
kind: Service
metadata:
  name: pihole-external
  namespace: default
spec:
  ports:
    - port: 8090
      targetPort: 8090
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pihole-external
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.50.212
    ports:
      - port: 8090
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: pihole-redirect
  namespace: default
spec:
  redirectRegex:
    regex: ^https://pihole\.homelab\.local/?$
    replacement: https://pihole.homelab.local/admin/
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pihole.homelab.local`) && Path(`/`)
      kind: Rule
      priority: 30
      middlewares:
        - name: pihole-redirect
      services:
        - name: pihole-external
          port: 8090
    - match: Host(`pihole.homelab.local`)
      kind: Rule
      priority: 10
      services:
        - name: pihole-external
          port: 8090
  tls:
    secretName: homelab-tls
